name: pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Setup Cargo Binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Setup Cargo Binaries
        run: |
          cargo binstall -y --force just
          cargo binstall -y --force trunk

      - name: Build Pages
        run: just web-build

      - name: Setup Pages Action
        uses: actions/configure-pages@v5

      - name: Upload Pages Artigact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './crates/web/dist'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
