name: test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Runs "cargo test --all-features" on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test -p svgo --all-features
